### PR TITLE
fix: support wchar_t and Unicode encoding in .list() parameters

### LINKED ISSUE #62: SerialPort.list() does not support Unicode encoding in ports' parameters values, replacing diacritics (accents) with �
### SerialPort Bindings Version

10.7.0

### Node Version

16.5.0

### Electron Version

_No response_

### Platform

Microsoft Windows NT 10.0.22000.0 x64

### Architecture

_No response_

### Hardware or chipset of serialport

_No response_

### What steps will reproduce the bug?

Simply running `SerialPort.list()` on a Windows system with the language set to one that has accents (diacritics). The list of ports will contain `�` characters in ports' properties instead of the accents.

### What happens?

Ports' list parameters encoding is broken for Unicode accents:
image

### What should have happened?

The ports list should properly encode all port parameters:
image

### Additional information

Seems like the `serialport_win` implementation uses `char`s, which do not encode Unicode characters on Windows. Instead, the implementation should use `wchar_t`s, which is the [preferred way](https://stackoverflow.com/a/402918/4618440) to store such data on Windows, substitute `std::string` with `std::wstring` and use the `Napi::String::New(Env, const char16_t*)` (since `wchar_t` is essentially a [16-bit wide Unicode character](https://docs.microsoft.com/en-US/cpp/cpp/char-wchar-t-char16-t-char32-t?view=msvc-170#remarks)) signature over `Napi::String::New(Env, const char*)` when passing these values to interpreted code.

### PR DESCRIPTION
**Pull request by artus9033**
Fixes #62

### CODE REVIEW

**Comment by artus9033** [comment]
I don't have a way to test that now, but according to [this](https://stackoverflow.com/a/11515035/4618440) it seems like `char`s outside of Windows do encode Unicode properly by default, so there should be no need to modify this implementation.

**Comment by gcampbell-msft** [comment]
@artus9033 @reconbot @HipsterBrown. 

Bringing this up again, is this a valid fix for the issue? If `char`s outside of Windows do encode Unicode properly by default, that's great, but this fix is for the `serialport_win.cpp`, right? 

I've made a comment [here](https://github.com/serialport/node-serialport/issues/2502#issuecomment-1192854562) regarding why I'm inquiring about a fix for this. We have a feature that has some issues posted for this and I noticed the [bug there](https://github.com/serialport/node-serialport/issues/2502) that hasn't gotten much traction. 

Let me know if there's any way I can help!

**Comment by artus9033** [comment]
> @artus9033 @reconbot @HipsterBrown.
> 
> Bringing this up again, is this a valid fix for the issue? If `char`s outside of Windows do encode Unicode properly by default, that's great, but this fix is for the `serialport_win.cpp`, right?
> 
> I've made a comment [here](https://github.com/serialport/node-serialport/issues/2502#issuecomment-1192854562) regarding why I'm inquiring about a fix for this. We have a feature that has some issues posted for this and I noticed the [bug there](https://github.com/serialport/node-serialport/issues/2502) that hasn't gotten much traction.
> 
> Let me know if there's any way I can help!

Indeed, it is the fix you are thinking of.
I believe your comment there is a bit off, as this is not about converting to UTF, but rather converting the code to a data structure that supports UTF. On Windows, `char` doesn't do that, but `wchar_t` does.

@reconbot are you going to review and merge this PR?

**Comment by gcampbell-msft** [comment]
@artus9033 Thanks for the comment and inquiring about it this is going to be merged. I'll keep an eye out for when this goes in!

**Comment by gcampbell-msft** [comment]
@reconbot @artus9033 Re-pinging this in the hope of getting it merged. Thanks!

**Comment by artus9033** [comment]
@reconbot is there any chance that this will be verified and merged? The problem still persists and there has been no progress with this PR in months.

**Pull request merged**
